### ISSUE TITLE
Content Issue

### ISSUE THREAD

**Issue by xjiang1** [Jlangway1/WebTech-Project#2]
1. Great design to make the size of all images identical on the Home Page. I recommend to adjust the width of paragraphs and images so that they match better with each other. 
2. On the Past Result page, maybe use lists or tables to show the results in structured text, so that it will be easier for users to read 
3. The font styles and font sizes of body are different on each page. I recommend to choose a specific font style and font size for different elements (such as h1, h2, p) to make the website looks better. 
4. Maybe choose to add a background color or a background image for all pages. So far the content looks good, but it is just a bit too plain. Adding background might help.

**Comment by Jlangway1** [comment]
Hi thanks for the input! 
First, I fixed the width of the paragraphs to better match each other.
Next, I added tables for the past results page to make it easier to read the scores.
I also took your advice to keep text fonts and sizes consistent. 
Finally, I decided to keep the background white since that was the original theme I wanted to go with!

Thanks again - Justin
